# Pretrain datasets
DS003029: '/your/path/ds003029/'                         # yes                # https://openneuro.org/datasets/ds003029/versions/1.0.7
DS003498: '/your/path/ds003498/'                         # yes                # https://openneuro.org/datasets/ds003498/versions/1.1.1/
DS003555: '/your/path/ds003555/'                         # yes                # https://openneuro.org/datasets/ds003555/versions/1.0.1
DS003844: '/your/path/ds003844/'                         # yes                # https://openneuro.org/datasets/ds003844/versions/1.0.3
DS003876: '/your/path/ds003876/'                         # yes                # https://openneuro.org/datasets/ds003876/versions/1.0.2 
DS004100: '/your/path/ds004100/'                         # yes                # https://openneuro.org/datasets/ds004100/versions/1.1.3
DS004752: '/your/path/ds004752/'                         # yes                # https://openneuro.org/datasets/ds004752/versions/1.0.1
DS005398: '/your/path/ds005398/'                         # yes                # https://openneuro.org/datasets/ds005398/versions/1.0.1
TUEP: '/your/path/TUEP/'                                             # yes                # https://isip.piconepress.com/projects/nedc/data/tuh_eeg/tuh_eeg_epilepsy/     
TUSZ: '/your/path/TUSZ/edf/'                                         # yes                # https://isip.piconepress.com/projects/nedc/data/tuh_eeg/tuh_eeg_seizure/
Siena: '/your/path/Siena/'                                           # yes                # https://physionet.org/content/siena-scalp-eeg/1.0.0/
JHCH_JHMCHH: '/your/path/JHCH_JHMCHH/'                               # yes                # https://www.kaggle.com/datasets/zjnueegdata/jhch-and-jhmchh-epileptic-dataset
Mendeley: '/your/path/Mendeley/'                                     # yes                # https://data.mendeley.com/datasets/5pc2j46cbc/1

# Downstream datasets
FNUSA: '/your/path/FNUSA_Mayo/DATASET_FNUSA/'   # FNUSA SOZ localization                   # https://figshare.com/collections/_/4681208
Mayo: '/your/path/FNUSA_Mayo/DATASET_MAYO/'                                                # https://figshare.com/collections/_/4681208
iEEG_bids_figshare: '/your/path/iEEG_bids_figshare/'                 # yes                # https://figshare.com/articles/dataset/_b_Annotated_b_b_interictal_epileptiform_discharges_in_b_b_intracranial_EEG_iEEG_sleep_data_b_/26131978?file=49884138
Zenodo_neonatal: '/your/path/Zenodo_neonatal/'                        # yes                # https://zenodo.org/records/1280684#.YQJpgI4zbIU
CUK_IMHANS: '/your/path/CUK_IMHANS/'                                 # yes                # https://data.mendeley.com/preview/mtpb9j8npf?a=344b0905-b2df-45e5-b41e-fe05d903ed11
CHB_MIT: '/your/path/CHB_MIT/physionet.org/files/chbmit/1.0.0/'      # yes                # https://physionet.org/content/chbmit/1.0.0/

# Output Path
DATASETS_OUTPUT_PATH: '~/ZRK/EpiNT/'