pretrain_dataset: '/your/path/dataset/pretrain_wo_sfreq_cpres_chn.hdf5'
RESULTS_DIR: '/your/path/'
experiment_name: 'pretrain'

# Model Parameters
model_name: 'EpiNT'
patch_mask: True
head_dropout: 0.1
task: 'pretrain' # pretrain

# Optimization Parameters
optimizer_name: 'AdamW'
lr_scheduler_type: 'linearwarmupcosinelr'
init_lr: 0.000002 # 2e-5
min_lr: 0.000001 # 1e-5
weight_decay: 0.05
warmup_lr: 0.000001 # 1e-5
warmup_steps: 1000
lr_decay_rate: 0.9
num_workers: 4
max_norm: 5.0

# Training Parameters
interval: 3000
max_opt_steps: 120000
max_epoch: 4
train_ratio: 0.9

# Data Parameters
train_batch_size: 1024

# Others
debug: True